version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: nest_cms_api
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./nest_cms_api.sql:/docker-entrypoint-initdb.d/nest_cms_api.sql